version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_admin_password
      POSTGRES_USER: admin
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - /var/lib/postgresql/data
